Repository jenkins-x/bucketrepo, pull requests merged in 2019-05, with the labels that each got.

#5 chore: fix error wrapping at tail of method
  internal/controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#6 feat: support HEAD requests
  internal/controller.go
  internal/http.go
Labels: approved, lgtm, ok-to-test, size/S

#7 feat: add the chart for the app
  .gitignore
  charts/jx-app-bucketrepo/.helmignore
  charts/jx-app-bucketrepo/Chart.yaml
  charts/jx-app-bucketrepo/Makefile
  charts/jx-app-bucketrepo/requirements.yaml
  charts/jx-app-bucketrepo/templates/NOTES.txt
  charts/jx-app-bucketrepo/templates/_helpers.tpl
  charts/jx-app-bucketrepo/templates/app.yaml
  charts/jx-app-bucketrepo/values.schema.json
  charts/jx-app-bucketrepo/values.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/L
