Repository jenkins-x/bucketrepo, pull requests merged in 2020-03, with the labels that each got.

#20 feat: add a pipeline for scanning the dependencies with whtiesource agent
  .whitesource.config
  internal/fs_storage.go
  jenkins-x-whitesource.yml
Labels: size/L

#21 chore: add linter and config
  hack/install_golint.sh
  hack/linter.sh
  internal/config.go
  internal/controller.go
  internal/main.go
  jenkins-x-lint.yml
Labels: size/L

#22 fix: replace the deprecated Deployment version
  charts/bucketrepo/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#23 fix: add missing selector
  charts/bucketrepo/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#24 fix: add helmfile bindings by default
  charts/bucketrepo/templates/_config.yaml.tpl
  charts/bucketrepo/templates/secret.yaml
  charts/bucketrepo/values.yaml
Labels: approved, size/S

#25 fix: conditional logic
  charts/bucketrepo/templates/_config.yaml.tpl
Labels: approved, size/XS

#26 fix: disable default storage
  charts/bucketrepo/values.yaml
Labels: approved, size/XS
