Repository jenkins-x/bucketrepo, pull requests merged in 2020-12, with the labels that each got.

#44 refactor: move to v3 requirements
  charts/bucketrepo/templates/_config.yaml.tpl
  charts/bucketrepo/values.yaml
Labels: approved, size/S

#45 chore: avoid map has no key error
  charts/bucketrepo/templates/_config.yaml.tpl
Labels: approved, size/XS

#46 fix: jx-secret populate error with missing storage map config
  charts/bucketrepo/templates/_config.yaml.tpl
Labels: approved, size/XS

#49 fix: helm3 + api-version: v2 support
  go.mod
  go.sum
  internal/chart_indexer.go
  internal/controller.go
  jenkins-x.yml
Labels: approved, ok-to-test, size/XL

#47 feat: add deployment secret env vars
  charts/bucketrepo/templates/deployment.yaml
  charts/bucketrepo/templates/env-secret.yaml
  charts/bucketrepo/values.yaml
Labels: approved, lgtm, ok-to-test, size/M
