Repository jenkins-x/bucketrepo, pull requests merged in 2021-05, with the labels that each got.

#56 fix: pipeline
  Makefile
Labels: approved, size/XS

#57 chore: fix pipeline
  charts/bucketrepo/Makefile
Labels: size/XS

#54 feat: add support for s3 compatible buckets
  README.md
  charts/bucketrepo/templates/config-secret.yaml
  charts/bucketrepo/values.yaml
Labels: approved

#58 chore: fix pipeline
  .lighthouse/jenkins-x/release.yaml
  hack/changelog-header.md
Labels: approved, size/S
